services:
  db:
    image: mysql
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
      - 'MYSQL_USER=manager'
    ports:
      - '3300:3306'
